In [1]:
import numpy as np


In [3]:
#prgm to convert list and tuple to array
lst1 = [1,2,3,4]
tup=(1,2,3)
np_array = np.array(lst1)
np_arr_tup=np.array(tup)
print(np_array)
print(np_arr_tup)

[1 2 3 4]
[1 2 3]


In [4]:
#prgm to find common vlues in 2 arrays
common_val=np.intersect1d(np_array,np_arr_tup)
print(common_val)

[1 2 3]


In [15]:
#prgm to compare 2 arrays using numpy
a=np.array([1,2,3,4])
b=np.array([9,2,4,5])
print("array a is:", a)
print("array b is :",b)
print('a is less than b')
print(np.less(a,b))
print('a is less than or equal to  b')
print(np.less_equal(a,b))
print('a is great than b')
print(np.greater(a,b))
print('a is greater than or =  b')
print(np.greater_equal(a,b))
print("a==b")
print(np.equal(a,b))



array a is: [1 2 3 4]
array b is : [9 2 4 5]
a is less than b
[ True False  True  True]
a is less than or equal to  b
[ True  True  True  True]
a is great than b
[False False False False]
a is greater than or =  b
[False  True False False]
a==b
[False  True False False]


In [30]:
#prgm to reverse an 1d array
a=np.array([1,5,8])
print(a)
print(np.flip(a))
print(a[::-1])
print(np.flipud(a))


[1 5 8]
[8 5 1]
[8 5 1]
[8 5 1]


In [29]:
#prgm to reverse an 2d> array
l1=[[1,2,3,4], [10,20,30,40]]
x=np.array(l1)
print(x)
print(np.fliplr(x))

[[ 1  2  3  4]
 [10 20 30 40]]
[[ 4  3  2  1]
 [40 30 20 10]]


In [60]:
# Write a Python program to check whether the
# numpy array is empty or not.
v=[1,2]
z=np.size(v)
if z==0:
    print('empty')
else:
    print('not empty')

not empty


In [40]:
# Write a Python program to check whether the
# numpy array is empty or not.
v=[]
flag= not np.any(x)
if flag==True:
    print('Array is empty ')
else:
    print('Array is not empty ')
    
    
# print(x)
# print(np.any(x))

Array is not empty 


    np.empty
    

In [51]:

# Write a Python program to how to add an extra
# column to a numpy array.
l1=[[1,2,3,4], [10,20,30,40]]
x=np.array(l1)
y=np.ones((2,1),dtype=np.int32)
z=np.append(x,y,axis=1)
print(x)
print(y)
print(z)

[[ 1  2  3  4]
 [10 20 30 40]]
[[1]
 [1]]
[[ 1  2  3  4  1]
 [10 20 30 40  1]]


In [58]:
# Write a Python program to how to add an extra
# column to a numpy array.
l1=[[1,2,3,4], [10,20,30,40]]
x=np.array(l1)
y=np.array((1,2)).reshape(2,1)
print(y)
z=np.append(x,y,axis=1)
print(z)

[[1]
 [2]]
[[ 1  2  3  4  1]
 [10 20 30 40  2]]


In [75]:
#How to swap two rows of an array?

l1=[[1,2,3,4], [10,20,30,40]]
x=np.array(l1)
print(x)
x[ [0, 1]] = x[ [1, 0]]
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]
[[10 20 30 40]
 [ 1  2  3  4]]


In [129]:
#Write a Python program to add, subtract,
#multiply, divide arguments element-wise.
print("add of 2 nums is:")
print(np.add(1,2))
print("sub of 2 nums is:")
print(np.subtract(10.4,2))
print("mul of 2 nums is:")
print(np.multiply(109,2))
print("div of 2 nums is:")
print(np.divide(10,2))


add of 2 nums is:
3
sub of 2 nums is:
8.4
mul of 2 nums is:
218
div of 2 nums is:
5.0


In [103]:
# Write a Python program to get the dates of
# yesterday, today and tomorrow.

t=(np.datetime64('today','D'))
print(f'today is {t}')
y=(np.datetime64('today','D')-np.timedelta64(1,'D'))
print(f'yday is {y}')  
tm=(np.datetime64('today','D')+np.timedelta64(1,'D'))
print(f'tmrw is {tm}')

today is 2022-06-29
yday is 2022-06-28
tmrw is 2022-06-30


In [118]:
# Write a Python program to change the
# dimension of an array.
listone=np.arange(1,49)
print(listone.shape)
print(np.ndim(listone))
reshapedim=listone.reshape(6,8)
print(reshapedim)
print(np.ndim(reshapedim))


(48,)
1
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]]
2


In [134]:
#https://het.as.utexas.edu/HET/Software/Numpy/reference/generated/numpy.seterr.html
listone=np.arange(1,49)
print(listone.shape)
np.seterr(all="ignore")
reshapedim=listone.reshape(3,8)
print(reshapedim)

(48,)


ValueError: cannot reshape array of size 48 into shape (3,8)

##### https://numpy.org/doc/stable/reference/arrays.datetime.html
print(np.array([0, 1577836800], dtype='datetime64[s]'))

In [121]:
# Write a Python program to convert a NumPy
# array into Python list structure.
l1=[[1,2,3,4], [10,20,30,40]]
x=np.array(l1)
print(x)
y=x.tolist()
print(y)

[[ 1  2  3  4]
 [10 20 30 40]]
[[1, 2, 3, 4], [10, 20, 30, 40]]


In [131]:
# Python program to create a random vector of
# size 10 and sort it.
x=np.random.randint(1,10,10)
print(x)
y=np.sort(x)
print(y)


[1 4 5 2 5 5 6 1 7 7]
[1 1 2 4 5 5 5 6 7 7]
