### Numpy (Numerical Python) Library

In [ ]:
# NumPy, short for Numerical Python, has long been a cornerstone of numerical computing in Python. It provides the data
# structures, algorithms, and library glue needed for most scientific applications involving numerical data in Python. 
# NumPy contains, among other things:

# ● A fast and efficient multidimensional array object ndarray
# ● Functions for performing element-wise computations with arrays or mathematical
# operations between arrays
# ● Tools for reading and writing array-based datasets to disk
# ● Linear algebra operations, Fourier transform, and random number generation
# ● A mature C API to enable Python extensions and native C or C++ code to access

In [ ]:
# NumPy’s data structures and computational facilities.

# Beyond the fast array-processing capabilities that NumPy adds to Python, one of its primary uses in data analysis is as a
# container for data to be passed between algorithms and libraries.

# For numerical data, NumPy arrays are more efficient for storing and manipulating data than the other built-in Python
# data structures. Also, libraries written in a lower-level language, such as C or Fortran, can operate on the data stored
# in a NumPy array without copying data into some other memory representation. Thus, many numerical computing tools for
# Python either assume NumPy arrays as a primary data structure or else target seamless interoperability with NumPy.

In [ ]:
# Why Numpy?
# One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on
# large arrays of data. There are a number of reasons for this:
# ● NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. NumPy’s
# library of algorithms written in the C language can operate on this memory without any type checking or other overhead. 
# NumPy arrays also use much less memory than built-in Python sequences.
# ● NumPy operations perform complex computations on entire arrays without the need for Python for loops. To give you an
# idea of the performance difference, consider a NumPy array of one million integers, and the equivalent Python list:

In [6]:
import numpy as np
np.random.seed(42)

nump_a = np.arange(1000000)
list_a = list(range(1000000))

print(len(nump_a))

print(len(list_a))

1000000
1000000


In [2]:
%%time

for x in range(10):
    nump_a2 = nump_a * 2

Wall time: 48.4 ms


In [3]:
%%time
for x in range(10):
    list_a2 = [x*2 for x in list_a]

Wall time: 2.05 s


In [ ]:
# The NumPy ndarray
# A Multidimensional Array Object One of the key features of NumPy is its N-dimensional array object, or ndarray, which is
# a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole
# blocks of data using similar syntax to the equivalent operations between scalar elements.

In [7]:
data = np.random.randint(1,10,24).reshape(2,3,4)

print(data)

[[[7 4 8 5]
  [7 3 7 8]
  [5 4 8 8]]

 [[3 6 5 2]
  [8 6 2 5]
  [1 6 9 1]]]


In [8]:
data1 = np.random.randint(1,10,24)

print(data1)


[3 7 4 9 3 5 3 7 5 9 7 2 4 9 2 9 5 2 4 7 8 3 1 4]


In [9]:
data2 = np.random.randint(1,10,24).reshape(4,6)
print(data2)

[[2 8 4 2 6 6]
 [4 6 2 2 4 8]
 [7 9 8 5 2 5]
 [8 9 9 1 9 7]]


In [10]:
# Note the appearance is of a 3 layer nested list. However, though they appear the same - these are arrays!! Important :
# note NO commas between the elements of the array. 

print(type(data))

for x in range(len(data)):
    for y in range(len(data[x])):
        for z in range(len(data[x][y])):
            print(data[x][y][z])
            
# The 3 dimensional array object is constructed of : 4 elements in each row, 3 rows nested in the 2nd dimension of the 
# array object and 2 such 2nd Dimension arrays nested in the outer most array block. 

<class 'numpy.ndarray'>
7
4
8
5
7
3
7
8
5
4
8
8
3
6
5
2
8
6
2
5
1
6
9
1


In [11]:
print(data)

[[[7 4 8 5]
  [7 3 7 8]
  [5 4 8 8]]

 [[3 6 5 2]
  [8 6 2 5]
  [1 6 9 1]]]


In [12]:
print(data * 10)

[[[70 40 80 50]
  [70 30 70 80]
  [50 40 80 80]]

 [[30 60 50 20]
  [80 60 20 50]
  [10 60 90 10]]]


In [13]:
# Note, we have not changed the original data ndarray.
print(data)

# We could change the original data variable by assigning the result to itself or to a new variable as usual.

[[[7 4 8 5]
  [7 3 7 8]
  [5 4 8 8]]

 [[3 6 5 2]
  [8 6 2 5]
  [1 6 9 1]]]


In [14]:
print(data+data)

[[[14  8 16 10]
  [14  6 14 16]
  [10  8 16 16]]

 [[ 6 12 10  4]
  [16 12  4 10]
  [ 2 12 18  2]]]


In [15]:
data1 = data*10

print(data1)

[[[70 40 80 50]
  [70 30 70 80]
  [50 40 80 80]]

 [[30 60 50 20]
  [80 60 20 50]
  [10 60 90 10]]]


In [ ]:
data1 = data1+data1
print(data1)

In [16]:
# An ndarray is a generic multidimensional container for homogeneous data; that is, all of the elements must be the same
# type. 

lst1 = ['a', 100, (20,30), {'x':10, 'y':20}]

np_arr = np.array(lst1)
print(np_arr)

['a' 100 (20, 30) {'x': 10, 'y': 20}]


In [17]:
np_arr = np.array(lst1, dtype = int)

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
# Unless explicitly specified, np.array tries to infer a good data type for the array that it creates.

In [18]:
lst2 = [2.0, 300, 72, 3.4, 5.78]

np_arr = np.array(lst2)

In [19]:
print(np_arr)
print(np_arr.dtype)

[  2.   300.    72.     3.4    5.78]
float64


In [20]:
lst3 = [2.13, 7.272, 3, 4.321, 11.234, 101]

np_arr2 = np.array(lst3)

print(np_arr2)
print(np_arr2.dtype)

print(type(np_arr2[2]))

[  2.13    7.272   3.      4.321  11.234 101.   ]
float64
<class 'numpy.float64'>


In [21]:
lst11 = [[1,2,4,4], [10,20,30,40]]

np_arr11 = np.array(lst11,dtype = int)
print(np_arr11)
print(type(np_arr11))

[[ 1  2  4  4]
 [10 20 30 40]]
<class 'numpy.ndarray'>


In [22]:
np_arr = np.random.randint(2,4,24)
print(np_arr)

[2 3 2 3 3 3 2 2 2 2 3 2 2 2 2 2 3 2 3 2 3 2 2 3]


In [23]:
np_arr_rs = np_arr.reshape(2,3,4)
print(np_arr_rs)

[[[2 3 2 3]
  [3 3 2 2]
  [2 2 3 2]]

 [[2 2 2 2]
  [3 2 3 2]
  [3 2 2 3]]]


In [24]:
# Every array has a shape, a tuple indicating the size of each dimension, and a dtype, an object describing the data
# type of the array:
print(data)
print(data.shape)

[[[7 4 8 5]
  [7 3 7 8]
  [5 4 8 8]]

 [[3 6 5 2]
  [8 6 2 5]
  [1 6 9 1]]]
(2, 3, 4)


In [25]:
print(data.dtype)

int32


In [26]:
# Creating ndarrays The easiest way to create an array is to use the array function. This accepts any sequence-like object
# (including other arrays) and produces a new NumPy array containing the passed data. For example, a list is a good
# candidate for conversion:

lst1 = [1,2,3,4]
        

nump_arr = np.array(lst1)

print(nump_arr)
print(type(nump_arr))
print(nump_arr.shape)
print(f'Dimensions of nump_arr is {nump_arr.ndim}.')

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
Dimensions of nump_arr is 1.


In [ ]:
# Note, how for a one dimensional array, the shape tuple is (4,) but the dimensions are 1.

In [27]:
nump_arr = nump_arr.reshape(1,4)

print(nump_arr.shape)
print(nump_arr.ndim)
print(nump_arr)

(1, 4)
2
[[1 2 3 4]]


In [ ]:
# Nested sequences, like a list of equal-length lists, will be converted into a multi-dimensional array:

In [28]:
lst2 = [[1,2,3,4], [10,20,30,40]]

nump_arr2 = np.array(lst2)

print(nump_arr2)
print(type(nump_arr2))
print(nump_arr2.shape)
print(f'Dimensions of nump_arr2 is {nump_arr2.ndim}.')

[[ 1  2  3  4]
 [10 20 30 40]]
<class 'numpy.ndarray'>
(2, 4)
Dimensions of nump_arr2 is 2.


In [29]:
print(nump_arr2)
nump_arr2

[[ 1  2  3  4]
 [10 20 30 40]]


array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [ ]:
# Note the output when outputting nump_arr2 on the notebook. It specifies that this is an array - but note the return of the
# comma!! It doesnt make a difference since we know that this is an array but just pointing out the difference in the 
# view of both commands.

In [ ]:
#asarray

In [30]:
import numpy as np

lst1 = [1,2,3,4]
np_array = np.array(lst1)
np_asarray = np.asarray(lst1)

print(np_array)
print(type(np_array))

print(np_asarray)
print(type(np_asarray))

[1 2 3 4]
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [40]:
lst1[0] = 100
print(lst1)

print(np_array)
print(np_asarray)

[100, 2, 3, 4]
[1 2 3 4]
[100   2   3   4]


In [41]:
np_array[0] = 107
print(np_array)
print(np_asarray)

[107   2   3   4]
[100   2   3   4]


In [42]:
np_array[0] = 1
print(np_array)

[1 2 3 4]


In [43]:
np_asarray[0] = 100
print(np_array)
print(np_asarray)


[1 2 3 4]
[100   2   3   4]


In [44]:
lst2 = [[1,2,3,4], [100,200,300,400]]

np_lst = np.array(lst2)

In [45]:
print(np_lst)


[[  1   2   3   4]
 [100 200 300 400]]


In [46]:
np_array_lst = np.array(np_lst)
np_asarray_lst = np.asarray(np_lst)

print(np_array_lst)
print(np_asarray_lst)

[[  1   2   3   4]
 [100 200 300 400]]
[[  1   2   3   4]
 [100 200 300 400]]


In [47]:
np_lst[0][0] = 1000

print(np_lst)
print(np_array_lst)
print(np_asarray_lst)

[[1000    2    3    4]
 [ 100  200  300  400]]
[[  1   2   3   4]
 [100 200 300 400]]
[[1000    2    3    4]
 [ 100  200  300  400]]


In [48]:
np_array_lst = np.array()

TypeError: array() missing required argument 'object' (pos 1)

In [49]:
# Before we go on - lets make the axis of Numpy clear. 
import numpy as np

arr = np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [50]:
arr1 = arr.reshape(3,8)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [51]:
arrx = np.arange(1,49)
arrx

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48])

In [52]:
arr2 = arrx.reshape(2,3,8)
arr2    

array([[[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48]]])

In [53]:
arr2x = np.arange(1,49).reshape(2,2,4,3)

arr2x

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]],


       [[[25, 26, 27],
         [28, 29, 30],
         [31, 32, 33],
         [34, 35, 36]],

        [[37, 38, 39],
         [40, 41, 42],
         [43, 44, 45],
         [46, 47, 48]]]])

In [54]:
print('arr :', arr, '\n','_'*125)
print('arr1 :', arr1, '\n','_'*125)
print('arr2 :', arr2, '\n','_'*125)

arr : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 
 _____________________________________________________________________________________________________________________________
arr1 : [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]] 
 _____________________________________________________________________________________________________________________________
arr2 : [[[ 1  2  3  4  5  6  7  8]
  [ 9 10 11 12 13 14 15 16]
  [17 18 19 20 21 22 23 24]]

 [[25 26 27 28 29 30 31 32]
  [33 34 35 36 37 38 39 40]
  [41 42 43 44 45 46 47 48]]] 
 _____________________________________________________________________________________________________________________________


In [55]:
arr2 = arr.reshape(2,3,4)
arr3 = arr.reshape(2,4,3)
arr4 = arr.reshape(4,3,2)
print('arr2 :', arr2, '\n','_'*125)
print('arr3 :', arr3, '\n','_'*125)
print('arr4 :', arr4, '\n','_'*125)

arr2 : [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 
 _____________________________________________________________________________________________________________________________
arr3 : [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]] 
 _____________________________________________________________________________________________________________________________
arr4 : [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]] 
 _____________________________________________________________________________________________________________________________


In [56]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [57]:
print('Sum Arr', np.sum(arr, axis = 0)) # 1D Array has no axis 1.

Sum Arr 300


In [58]:
print(arr4)




[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [59]:
print(np.sum(arr4))

300


In [60]:
print(arr4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [61]:
print('sum Axis 0', np.sum(arr4, axis = 0))

sum Axis 0 [[40 44]
 [48 52]
 [56 60]]


In [62]:
print(arr4)
print(arr4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
(4, 3, 2)


In [63]:
print(arr4)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [64]:
arr_col = np.sum(arr4, axis = 1)
print(arr_col)
print(arr_col.shape)

[[ 9 12]
 [27 30]
 [45 48]
 [63 66]]
(4, 2)


In [65]:
print(arr4)

print('Sum Axis 2', np.sum(arr4, axis = 2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
Sum Axis 2 [[ 3  7 11]
 [15 19 23]
 [27 31 35]
 [39 43 47]]


In [66]:
arr6 = np.arange(1,13).reshape(3,2,2)

print(arr6)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [67]:
arr = np.arange(1,49)
arr5 = arr.reshape(3,4,2,2)
print('arr5 :', arr5)
print('Sum Axis 3', np.sum(arr5, axis = 0))

arr5 : [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]


 [[[17 18]
   [19 20]]

  [[21 22]
   [23 24]]

  [[25 26]
   [27 28]]

  [[29 30]
   [31 32]]]


 [[[33 34]
   [35 36]]

  [[37 38]
   [39 40]]

  [[41 42]
   [43 44]]

  [[45 46]
   [47 48]]]]
Sum Axis 3 [[[51 54]
  [57 60]]

 [[63 66]
  [69 72]]

 [[75 78]
  [81 84]]

 [[87 90]
  [93 96]]]


In [69]:
print(arr6)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [70]:
print(np.sum(arr6,axis = 2))

[[ 3  7]
 [11 15]
 [19 23]]


In [71]:
print(np.sum(arr6, axis = 1))

[[ 4  6]
 [12 14]
 [20 22]]


In [72]:
print(np.sum(arr6))

78


### Homogeneous n-dimensional vectors:

In addition to np.array, there are a number of other functions for creating new arrays. As examples, zeros and ones create arrays of 0s or 1s, respectively, with a given length or shape(using tuples for shape).

In [73]:
np_zero = np.zeros(10)

print(np_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [74]:
np_zero6x2 = np.zeros((2,6))

print(np_zero6x2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#Note above how the shape is a tuple. 

In [75]:
np_one = np.ones(10)
print(np_one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [76]:
np_one6x2 = np.ones((2,6))

print(np_one6x2)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [77]:
np_full_5 = np.full(10,5)

print(np_full_5)

[5 5 5 5 5 5 5 5 5 5]


In [78]:
np_full_a = np.full(10, 'a')

In [79]:
print(np_full_a)

['a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a' 'a']


In [80]:
np_full6x2_5 = np.full((2,6), 5)

print(np_full6x2_5)

[[5 5 5 5 5 5]
 [5 5 5 5 5 5]]


In [ ]:
# Empty creates an array without initializing its values to any particular value. To create a higher dimensional array
# with these methods, use a tuple for shape.

In [95]:
import numpy as np

np_empty = np.empty(10)
print(np_empty)

[7.74860419e-304 7.29290208e-304 7.74860419e-304 7.74860419e-304
 7.74860419e-304 7.74860419e-304 7.74860419e-304 2.13031734e-314
 0.00000000e+000 7.74860419e-304]


In [96]:
np_empty6x2 = np.empty((2,6))
print(np_empty6x2)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [91]:
#Note that the numpy empty does not actually have empty values - it does create the array of desired shape and size but with
# arbitary values. It is slightly faster to initialise than np.zeros and np.ones especially for larger arrays. 

#### Note that for each of np.zeros, np.ones, np.full and np.empty there are np.zeros_like, ones_like, full_like and empty_like which behave just like the difference between np.array and np.asarray i.e. if the matrix is already an array, then does not create a copy but just gives array like funcitonality.

In [ ]:
#Matrix Functions

In [97]:
#1. The identity matrix:
# In linear algebra, the identity matrix of size n is the n × n square matrix with ones on the main diagonal and zeros
# elsewhere.

np_id = np.identity(5)

print(np_id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Note that by default the 1s and 0s are float type. 

In [98]:
np_id_int = np.identity(5, dtype = int)

print(np_id_int)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [99]:
np_id_bool = np.identity(5,dtype= bool)

print(np_id_bool)

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


In [100]:
# 2. Function ‘eye’:
# It is used to return a 2-D array with ones on the diagonal and zeros elsewhere. Unlike identity, array does not necessarily
# have to be square.

np_eye_1 = np.eye(3)

print(np_eye_1)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [101]:
np_eye_5x4 = np.eye(5,4)

print(np_eye_5x4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
# We can also specify the diagnol in the eye function unlike the identity function. 0 is the default, Positive values are
# integers above the main diagonal and negative values are integers below the main diagonal. 

In [102]:
np_eye_8x6_0 = np.eye(6,6,0)

print(np_eye_8x6_0)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [103]:
np_eye_8x6_p1 = np.eye(6,6,1)

print(np_eye_8x6_p1)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [104]:
np_eye_8x6_p2 = np.eye(6,6,2)

print(np_eye_8x6_p2)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [105]:
np_eye_8x6_n1 = np.eye(6,6,-1)

print(np_eye_8x6_n1)

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [106]:
np_eye_8x6_n2 = np.eye(6,6,00)

print(np_eye_8x6_n2)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# 3. Function diag:
# The diag function takes two arguments:
# ● An ndarray v.
# ● An integer k (default = 0). If ‘v’ is dimension is 1 then the function constructs a matrix where its diagonal number k 
# is formed by the elements of the vector ‘v’. If a is a matrix (dimension 2) then the function extracts the elements of
# the kth diagonal in a one-dimensional vector.

In [107]:
np_diag = np.diag([1,5,7])

print(np_diag)

[[1 0 0]
 [0 5 0]
 [0 0 7]]


In [108]:
np_array_1 = np.ones((3,3))*5
print(np_array_1)

np_diag1 = np.diag(np_array_1)
print(np_diag1)

np_array_1 = np.diag([1,3,5])
print(np_array_1)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[5. 5. 5.]
[[1 0 0]
 [0 3 0]
 [0 0 5]]


In [109]:
np_diag1 = np.diag(np_array_1)

print(np_array_1)

[[1 0 0]
 [0 3 0]
 [0 0 5]]


In [110]:
print(np_diag1)

[1 3 5]


In [111]:
np_arr_lst = np.array([[1,2,3], [10,20,30], [100,200,300]])

print(np_arr_lst)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [112]:
np_diag_l = np.diag(np_arr_lst)

print(np_diag_l)

[  1  20 300]


In [115]:
np_diag_2 = np.diag(np_arr_lst, 1)

print(np_diag_2)

[ 2 30]


In [116]:
# 4. Function ‘fromfunction’:
# Construct an array by executing a function over each coordinate. Let’s create a vector-based on its indices.

np_ffunc = np.fromfunction(lambda x,y,z : x-y+z, (3,3,3))
# 0,0,0  0,0,1  0,0,2
# 0,1,0  0,1,1, 0,1,2
# 0,2,0, 0,2,1, 0,2,2

# 1,0,0  0,0,1  0,0,2
# 1,1,0  0,1,1, 0,1,2
# 1,2,0, 0,2,1, 0,2,2

# 2,0,0  0,0,1  0,0,2
# 2,1,0  0,1,1, 0,1,2
# 2,2,0, 0,2,1, 0,2,2

print(np_ffunc)

[[[ 0.  1.  2.]
  [-1.  0.  1.]
  [-2. -1.  0.]]

 [[ 1.  2.  3.]
  [ 0.  1.  2.]
  [-1.  0.  1.]]

 [[ 2.  3.  4.]
  [ 1.  2.  3.]
  [ 0.  1.  2.]]]


In [ ]:
#Remember here that the co-ordinates x,y for each element are as follows:

0,0   0,1   0,2
1,0   1,1   1,2
2,0   2,1   2,2

In [117]:
np_ffuncXY2 = np.fromfunction(lambda x,y : x*y+2, (3,3))

print(np_ffuncXY2)

# 0,0,0  0,0,1  0,0,2
# 0,1,0  0,1,1, 0,1,2
# 0,2,0, 0,2,1, 0,2,2

# 1,0,0  0,0,1  0,0,2
# 1,1,0  0,1,1, 0,1,2
# 1,2,0, 0,2,1, 0,2,2

# 2,0,0  0,0,1  0,0,2
# 2,1,0  0,1,1, 0,1,2
# 2,2,0, 0,2,1, 0,2,2

[[2. 2. 2.]
 [2. 3. 4.]
 [2. 4. 6.]]


In [118]:
import numpy as np

np_ffunct_gte = np.fromfunction(lambda x,y : x >= y, (3,3))

print(np_ffunct_gte)

[[ True False False]
 [ True  True False]
 [ True  True  True]]


In [119]:
# Aggregation methods:

np_sample = np.arange(24).reshape(2,3,4)

print(np_sample)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [120]:
test = list(range(1,20,0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [121]:
test1 = np.arange(1,5,0.2)

print(test1)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8]


In [122]:
# ● ndarray.sum: Return the sum of the array elements over the given axis.
print(np_sample)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [123]:
print(np_sample.sum()) # - With no axis specified, sums all the elements of the 0 axis.

276


In [124]:
np_s_a0 = np_sample.sum(0) # - with axis specified sums elements of specified axis or you could say collapses specified axis

print(np_s_a0)
print(np_s_a0.ndim)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
2


In [125]:
print(np_sample)
print(np_sample.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


In [126]:
np_s_a1 = np_sample.sum(1)

print(np_s_a1)
print(np_s_a1.ndim)

[[12 15 18 21]
 [48 51 54 57]]
2


In [127]:
np_s_a2 = np_sample.sum(2)

print(np_s_a2)
print(np_s_a2.ndim)

[[ 6 22 38]
 [54 70 86]]
2


In [128]:
print(np_sample)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [129]:
# ● ndarray.product: Return the product of the array elements over the given axis.

np_sample_2 = np.arange(1,11).reshape(2,5)

print(np_sample_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [130]:
np_prod = np_sample_2.prod()

print(np_prod)

3628800


In [131]:
print(np_sample_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [132]:
np_prod_0 = np_sample_2.prod(0)

print(np_prod_0)

[ 6 14 24 36 50]


In [133]:
np_prod_1 = np_sample_2.prod(1)

print(np_prod_1)

[  120 30240]


In [134]:
np_rand_sample = np.random.randint(1,100,24).reshape(2,3,4)

print(np_rand_sample)

[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [ ]:
# ● ndarray.max: Return the maximum along the given axis.
# ● ndarray.argmax: Return indices of the maximum values along the given axis

In [135]:
print(np_rand_sample.max()) #without any axis - maximum of array

print(np_rand_sample.argmax()) # Index position of maximum number - without any axis > index value of max number (flattened
# array)

print(np_rand_sample.flatten())

99
8
[12 34 33 48 23 62 88 37 99 44 86 91 35 65 99 47 78  3  1  5 90 14 27  9]


In [136]:
print(np_rand_sample)


[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [138]:
print(np_rand_sample.max(0)) # with axis 0

print(np_rand_sample.argmax(0)) # with axis 0

[[35 65 99 48]
 [78 62 88 37]
 [99 44 86 91]]
[[1 1 1 0]
 [1 0 0 0]
 [0 0 0 0]]


In [139]:
print(np_rand_sample)

[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [140]:
print(np_rand_sample.max(1))
print(np_rand_sample.argmax(1))


[[99 62 88 91]
 [90 65 99 47]]
[[2 1 1 2]
 [2 0 0 0]]


In [141]:
print(np_rand_sample)

[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [142]:
print(np_rand_sample.max(2))
print(np_rand_sample.argmax(2))

[[48 88 99]
 [99 78 90]]
[[3 2 0]
 [2 0 0]]


In [143]:
print(np_rand_sample)


[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [ ]:
# ● ndarray.min: Return the minimum along the given axis.
# ● ndarray.argmin: Return indices of the minimum values along the given axis.

In [144]:
print(np_rand_sample.min())
print(np_rand_sample.argmin())
print(np_rand_sample.flatten())

1
18
[12 34 33 48 23 62 88 37 99 44 86 91 35 65 99 47 78  3  1  5 90 14 27  9]


In [145]:
print(np_rand_sample)

[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [146]:
print(np_rand_sample.min(0))
print(np_rand_sample.argmin(0))

[[12 34 33 47]
 [23  3  1  5]
 [90 14 27  9]]
[[0 0 0 1]
 [0 1 1 1]
 [1 1 1 1]]


In [ ]:
print(np_rand_sample)

In [ ]:
print(np_rand_sample.min(1))
print(np_rand_sample.argmin(1))

In [ ]:
print(np_rand_sample.min(2))
print(np_rand_sample.argmin(2))

In [147]:
# ● ndarray.mean: Returns the average of the array elements along the given axis.

print(np_rand_sample)

[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [148]:
print(np_rand_sample.mean()) #without axis - mean of all elements.

47.083333333333336


In [ ]:
print(np_rand_sample.mean(0))

In [ ]:
print(np_rand_sample.mean(1))

In [ ]:
print(np_rand_sample.mean(2))

In [ ]:
# ● ndarray.cumsum: Return the cumulative sum of the elements along the given axis.

In [149]:
print(np_rand_sample)

[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [150]:
print(np_rand_sample.cumsum())

[  12   46   79  127  150  212  300  337  436  480  566  657  692  757
  856  903  981  984  985  990 1080 1094 1121 1130]


In [151]:
print(np_rand_sample.cumsum(0))

[[[ 12  34  33  48]
  [ 23  62  88  37]
  [ 99  44  86  91]]

 [[ 47  99 132  95]
  [101  65  89  42]
  [189  58 113 100]]]


In [152]:
print(np_rand_sample.cumsum(1))

[[[ 12  34  33  48]
  [ 35  96 121  85]
  [134 140 207 176]]

 [[ 35  65  99  47]
  [113  68 100  52]
  [203  82 127  61]]]


In [153]:
print(np_rand_sample)


[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [ ]:
print(np_rand_sample.cumsum(2))

In [ ]:
# ● ndarray.cumprod: Return the cumulative product of the elements along the given axis.

In [ ]:
np_sample_cd = np.random.randint(1,10, 12).reshape(2,2,3)

print(np_sample_cd)

In [ ]:
print(np_sample_cd.cumprod())

In [ ]:
print(np_sample_cd.cumprod(0))

In [ ]:
print(np_sample_cd)

In [ ]:
print(np_sample_cd.cumprod(1))

In [ ]:
print(np_sample_cd.cumprod(2))

In [ ]:
# ● ndarray.var: Returns the variance of the array elements, along the given axis.
# ● ndarray.std: Returns the standard deviation of the array elements along the given axis.

In [154]:
print(np_rand_sample)

[[[12 34 33 48]
  [23 62 88 37]
  [99 44 86 91]]

 [[35 65 99 47]
  [78  3  1  5]
  [90 14 27  9]]]


In [155]:
print('Variance : ', np_rand_sample.var())
print('Standard Deviation : ', np_rand_sample.std())

Variance :  1044.7430555555554
Standard Deviation :  32.32248529360877


In [156]:
print('Variance')
print(np_rand_sample.var(0))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(0))

Variance
[[1.32250e+02 2.40250e+02 1.08900e+03 2.50000e-01]
 [7.56250e+02 8.70250e+02 1.89225e+03 2.56000e+02]
 [2.02500e+01 2.25000e+02 8.70250e+02 1.68100e+03]]
-----------------------------------------------------------------------------------------------------------------------------
Standard Deviation
[[11.5 15.5 33.   0.5]
 [27.5 29.5 43.5 16. ]
 [ 4.5 15.  29.5 41. ]]


In [ ]:
print('Variance')
print(np_rand_sample.var(1))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(1))

In [ ]:
print('Variance')
print(np_rand_sample.var(2))

print('-'*125)

print('Standard Deviation')
print(np_rand_sample.std(2))

### Data Types for ndarrays

In [ ]:
# The data type or dtype is a special object containing the information (or metadata, data about data) the ndarray needs to
# interpret a chunk of memory as a particular type of data:

In [157]:
import numpy as np
import sys
np_arr1 = np.array([1,2,3], dtype = 'float16')

In [158]:
print(np_arr1.dtype)
print(np_arr1)

float16
[1. 2. 3.]


In [159]:
np_arr2 = np.array([10,-4,3], dtype = 'int8')

print(np_arr2.dtype)
print(np_arr2)

print(sys.getsizeof(np_arr2[0]))
print(sys.getsizeof(10))

int8
[10 -4  3]
25
28


In [ ]:
# Type              Type code           Description
# int8, uint8       i1, u1              Signed and unsigned 8-bit (1byte) integer types
# int16, uint16     i2, u2              Signed and unsigned 16-bit integer types
# int32, uint32     i4, u4              Signed and unsigned 32-bit integer types
# int64, uint64     i8, u8              Signed and unsigned 64-bit integer types
# float16           f2                  Half-precision floating point
# float32           f4 or f             Standard single-precision floating point; compatible with C float
# float64           f8 or d             Standard double-precision floating point; compatible with C double
#                                       and Python float object
# float128          f16 or g            Extended-precision floating point
# complex64,        c8, c16, c32        Complex numbers represented by two 32, 64, or 128 floats respectively
# complex128,
# complex256
# bool              ?                   Boolean type storing True and False values
# object            O                   Python object type; a value can be any Python object
# string_           S                   Fixed-length ASCII string type (1 byte per character); for example, to create a
#                                       string dtype with length 10, use 'S10'
# unicode_          U                   Fixed-length Unicode type (number of bytes platform specific); same specification
#                                       semantics as string_ (e.g., 'U10')

# Note: It’s important to be cautious when using the numpy string_ type, as string data in NumPy is fixed size and may
# truncate input without warning

### Arithmetic with NumPy

In [ ]:
# Arrays Arrays are important because they enable you to express batch operations on data without writing any for loops. 
# NumPy users call this vectorization. Any arithmetic operations between equal-size arrays applies the operation
# element-wise:

In [160]:
np_arr1 = np.array([[1,2,3], [4,5,6]])

np_arr2 = np.array([[2,4,6], [8,10,12]])

print(np_arr1)
print(np_arr2)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [161]:
print(np_arr1 * np_arr2)

[[ 2  8 18]
 [32 50 72]]


In [162]:
print(np_arr2 - np_arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [ ]:
print(np_arr1)

In [ ]:
print(1/(np_arr1**2))

In [ ]:
print(np_arr1)
print(np_arr2)

In [ ]:
print(np_arr1 * np_arr2)

In [ ]:
print((np_arr1*np_arr2)**1/2)

In [ ]:
# Comparisons between arrays of the same size yield boolean arrays:

In [ ]:
print(np_arr1)
print(np_arr2)

print(np_arr1 < np_arr2)

In [163]:
arrtest = np.arange(1,11).reshape(2,5)

arrtest

print(arrtest.ndim)
print(arrtest)

2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [164]:
# Uncommon dimensions arrays are 'broadcast'. E.g.

import numpy as np

# However, broadcasting needs to follow certain rules. 

# Arrays are broadcastable if:

# Arrays have exactly the same shape.

np_arr_so = np.arange(1,7).reshape(3,2)
np_arr_lo = np.arange(10,70,10).reshape(3,2)

print(np_arr_so)
print(np_arr_lo)

[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]
 [50 60]]


In [ ]:
print(np_arr_so*np_arr_lo)

In [ ]:
# Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.

np_arr_so = np.arange(3).reshape(1,3)
print(np_arr_so)

In [ ]:
np_arr_lo = np.arange(0,60,10).reshape(2,3)
print(np_arr_lo)

In [ ]:
print(np_arr_so*np_arr_lo)

In [ ]:
arr_lo = np.arange(1,385).reshape(2,4,6,8)
arr_so = np.arange(1,17).reshape(2,1,1,8)

print(arr_lo * arr_so)

In [ ]:
np_arr_lo = np.arange(0,60,10).reshape(3,2)
np_arr_so = np.arange(2).reshape(1,2)

print(np_arr_lo)
print(np_arr_so)

In [ ]:
print(np_arr_lo*np_arr_so)

In [ ]:
np_arr_so = np.arange(6).reshape(1,2,3)
np_arr_so

In [ ]:
np_arr_lo = np.arange(0,120,10).reshape(2,2,3)
np_arr_lo

In [ ]:
print(np_arr_so+np_arr_lo)

In [ ]:
# Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated
# property is true.

np_arr_so = np.arange(1,7).reshape(1,2,3)
print(np_arr_so)

In [ ]:
np_arr_lo = np.arange(1,19).reshape(3,2,3)
print(np_arr_lo)

In [ ]:
np_arr_so*np_arr_lo

In [ ]:
np_arr_so = np_arr_so.reshape(1,2,3)
print(np_arr_so)


In [ ]:
print(np_arr_lo)

In [ ]:
print(np_arr_so*np_arr_lo)

In [ ]:
# However, broadcasting follows certain rules:

# Array with smaller ndim than the other is prepended with '1' in its shape.

# Size in each dimension of the output shape is maximum of the input sizes in that dimension.

# An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly
# 1.

# If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that
# dimension.

### Basic Indexing and Slicing

In [ ]:
#NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual
# elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [ ]:
arr1 = np.arange(10)
print(arr1)

In [ ]:
print(arr1[5])

In [ ]:
print(arr1[2:4])

In [ ]:
# Slice assignment

arr1[2:4] = 11

print(arr1)

In [ ]:
list1 = list(range(10))
print(list1)
list1[2:4] = 11,
print(list1)

In [ ]:
# As you can see, if you assign a scalar value to a slice of an array, as in arr[2:4] = 11, the value is propagated (or 
# broadcasted henceforth) to the entire selection. While for lists, the value(s) of the iterable replace(s) the slice.

In [ ]:
# An important first distinction from Python’s built-in lists is that array slices are views on the original array. This
# means that the data is not copied, and any modifications to the view will be reflected in the source array. To give
# an example of this, first create a slice of arr:

In [ ]:
arr = np.arange(11)
arr_slice = arr[5:8]
print(arr_slice)

In [ ]:
arr_slice[1] = 6789
print(arr_slice)
print(arr)

In [ ]:
list1 = list(range(11))
lst_slice = list1[5:8]
print(lst_slice)

In [ ]:
lst_slice[1] = 6789
print(lst_slice)
print(list1)

In [ ]:
# To copy an array or its slice you have to exlicitly copy.

In [ ]:
arr = np.arange(11)
print(arr)
arr_slice = arr[5:8].copy()

print(arr_slice)

In [ ]:
arr_slice[1] = 6789

print(arr_slice)
print(arr)

In [ ]:
# Accessing values in nested arrays.

In [ ]:
arr_hdim = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr_hdim)

In [ ]:
print(arr_hdim[1][1])

In [ ]:
# Numpy allows you to use easier syntax to access elements in nested arrays.

print(arr_hdim[1,0])

In [ ]:
#Indexing with slices

#Like one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax:

arr = np.arange(11)
arr

In [ ]:
print(arr[1:6])

In [ ]:
# Consider a two-dimensional array. Slicing this array is a bit different:
 
arr_2d = np.array([[1,2,3], [4,5,6],[7,8,9]])

print(arr_2d)

In [ ]:
print(arr_2d[:2])

In [ ]:
# As we see, the array has been sliced on axis 0

In [ ]:
# As the syntax for multiple indexes seen previously, we can pass multiple slices as well. 

print(arr_2d[:2])
print(arr_2d[:2, :2])

In [ ]:
arr_2d

In [ ]:
# or

print(arr_2d[:2,1:])

In [ ]:
# When slicing like this, you always obtain array views of the same number of dimensions

In [ ]:
# By mixing integer indexes and slices, you get lower dimensional slices

In [ ]:
print(arr_2d)

In [ ]:
print(arr_2d[1,1:])

In [ ]:
# Here we first selected the 1st index on axis 0 and then sliced from 1st index to end along axis 1

In [ ]:
# Another example, slice from 1st index to end along axis 0 and then index 2 along axis 1
print(arr_2d[1:])

print(arr_2d[1:,2])

### Boolean Indexing

In [ ]:
# Let’s consider an example where we have some data in an array and an array of names with duplicates. 

In [ ]:
names = np.array(['Bob', 'John', 'Steve', 'Will', 'Bob', 'Steve', 'Bob'])
print(names)

In [ ]:
# Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized. Thus, comparing names with
# the string 'Bob' yields a boolean array:
print(names == 'Bob')

In [ ]:
data = np.random.randint(1,10,49).reshape(7,7)

print(data)

In [ ]:
# We can use the values from the boolean array returned from the comparison operator == performed on 'names' array to 
# index from another array data.

In [ ]:
print(names=='Bob')

In [ ]:
print(data[1, names == 'Bob'])

In [ ]:
print(data[names == 'Bob'])

In [ ]:
print(data[names == 'Bob', names=='Bob'])

In [ ]:
# Arange function in Numpy. Takes 4 arguments

#1. Start - Optional - defaults to 0
#2. Stop - Mandatory
#3. Step - Optional - Defaults to 1 but can take floating point numbers as a step (Unlike built-in range function of Python)
#4. dtype - Optional


np_arr_dec = np.arange(1,3,0.1)

print(np_arr_dec)

In [ ]:
range_1 = list(range(1,3,0.1))
print(list(range_1))

In [ ]:
range_2 = list(range(1,3,1))
print(list(range_2))

In [ ]:
# linspace function - returns evenly spaced equidistant number numbers between a specified range.

In [ ]:
# It takes 7 arguments.

#1. Start - Mandatory
#2. Stop - Mandatory
#3. Num - Optional - Number of samples required between the range/interval. By default set to 50
#4. endpoint - Optional - By default set to true and includes the endpoint(i.e. stop value) - if set to False, returns
# equidistant numbers not including the endpoint/stop value.
#5 retstep - Optional - Default is False. If set to true, returns the samples and the step value (distance between samples)
#6 dtype - Optional - By default datatype will be inferred. However, for int datatype, float will be considered even if 
# start and stop are int.
#7 axis - Optional - By default 0 axis. Only useful in case start and stop are array-like.



In [ ]:
arr_lin = np.linspace(1,10)

print(arr_lin)

In [ ]:
# By default creates 50 equidistant samples / points

In [ ]:
arr_lin10 = np.linspace(1,20,5) # with num of samples specified

print(arr_lin10)

In [ ]:
arr_lin10_noEP = np.linspace(1,20,5, endpoint=False) #No Endpoint included

In [ ]:
print(arr_lin10_noEP)

In [ ]:
arr_lin10_noEP_wRS = np.linspace(1,20,5, endpoint=False, retstep=True) #With array as 1st element and step value as 2nd
                                                                       # element of tuple.
print(arr_lin10_noEP_wRS)
print(type(arr_lin10_noEP_wRS))

In [ ]:
arr_lin10_int = np.linspace(1,20,5, dtype = int) # With dtype specified.
print(arr_lin10_int)

In [ ]:
arr_like_lin10 = np.linspace((1,2), (3,4), 10) # Array like start and stop values.
print(arr_like_lin10)

#Note here that default axis is 0. The equidistant numbers are being added along 0 axis

In [ ]:
arr_like_lin10_ax1 = np.linspace((1,2), (3,4), 10, axis=1) # with equidistant samples added along axis 1

print(arr_like_lin10_ax1)

### Random Module in Numpy

In [ ]:
#Randint to generate a random integer

result = np.random.randint(1,10,5)

print(result)

# Returns random numbers between specified range and number of values specified in third parameter

In [ ]:
print(np.random.randint(1,10)) # Prints 1 number between 0 and 9 - Start not specified defaults to 0, number not specified 
                             # defaults to 1.

In [ ]:
#rand - For random float values between 0 and 1 only.

result = np.random.rand()

print(result)



In [ ]:
print(np.random.rand(3,2,4)) # Can take shape as parameter. Here will return 3 arrays on axis 0, 2 on 1 and 4 on 2

In [ ]:
#randn function - returns float values in given shape array from a standard normal distribution i.e. 

# Roughly - 65% of the values will be between -1 to 1
# Roughly - 95% of the values will be between -2 to 2
# Roughly - 99% of the values will be between -3 to 3

# If no shape provided will return a single float value.

result = np.random.randn(3,3,3)

print(result)

In [ ]:
arr1 = np.arange(10)
arr1

In [ ]:
#choice - Choose a random number from an array or integer. 

# Takes only one 1D array or an integer as input from which to chose. 

choice = np.random.choice(arr1)

print(choice)

In [ ]:
choice = np.random.choice(10) # If an integer x is specified - treats it as a choice in np.arange(x) i.e from 0 to x-1 e.g.
                              # here - it will choose between 0 to 9.
    
print(choice)

In [ ]:
choice = np.random.choice(arr1, 5) # Size of choice specified.
print(choice)

In [ ]:
# By default - replace parameter is True i.e. if a number has been chosen, it will be put back in the array and has a chance
# to be chosen again. By setting to false - the number is removed from array and wont be chosen again.

choice = np.random.choice(arr1, 10, replace = False)

print(choice)

In [ ]:
# The p parameter takes probabilities i.e. if I had numbers 1 to 5 - in a uniform distribution each would have a 20% chance
# or (0.2 probability). However, if we were to specify the probabilities, it will take those probabilities into account
# while generating random numbers

choice = np.random.choice(np.arange(3), p = [0.1,0.2,0.7], size = 10)

print(choice)

In [ ]:
#permutation - Returns a random permutation of input array or if integer specified random permutation of np.arrange(integer)

perm = np.random.permutation(10)

print(perm)

In [ ]:
arr = np.arange(24).reshape(4,3,2)
print(arr)

In [ ]:
perm_arr = np.random.permutation(arr) #
print(perm_arr)


# For a multidimensional array - it is only shuffled along the 0 index axis.

In [ ]:
arr = np.arange(10)
print(arr)

In [ ]:
#any - Returns true if any of the elements in the array are true. 
#all Returns true if all of the elements in the array are true.

In [ ]:
print(np.any(arr))
print(np.all(arr))

In [ ]:
arr_zero = np.zeros(5)

print(np.any(arr_zero))
print(np.all(arr_zero))

In [ ]:
arr_alt = np.random.randint(0,2,5)

print(arr_alt)

In [ ]:
print(np.any(arr_alt))
print(np.all(arr_alt))

In [ ]:
arr_zero_grid = np.zeros((2,3))

print(np.any(arr_zero_grid))
print(np.all(arr_zero_grid))

In [ ]:
arr_one_grid = np.ones((2,3))
print(arr_one_grid)
print(np.any(arr_one_grid))
print(np.all(arr_one_grid))

In [ ]:
arr = np.arange(11)
arr10 = np.arange(11,21)
print(arr)
print(arr10)

In [ ]:
# Append

arr_n_10 = np.append(arr, arr10)
print(arr_n_10)

In [ ]:
arr_1 = np.arange(1,11).reshape(2,5)
arr_2 = np.arange(21,31).reshape(2,5)

print(arr_1)
print(arr_2)

In [ ]:
arr_1n2 = np.append(arr_1, arr_2, axis = 1)

print(arr_1n2)

In [ ]:
arr_1n2V = np.append(arr_1, arr_2, axis = 0)

print(arr_1n2V)

In [ ]:
#vstack - stacks arrays vertically

arr_V = np.vstack((arr_1, arr_2))
print(arr_V)

In [ ]:
arr1x = np.arange(1,6)
arr2x = np.arange(11,16)
print(arr1x)
print(arr2x)

In [ ]:
arr_vx = np.vstack((arr1x, arr2x))
arr_vx


In [ ]:
arr_apx = np.append(arr1x, arr2x, axis = 1)

arr_apx

In [ ]:
arr_H = np.hstack((arr1x, arr2x))

print(arr_H)

In [ ]:
#sort

arr_rand = np.random.randint(1,10, 20).reshape(4,5)
print(arr_rand)

In [ ]:
arr_sort = np.sort(arr_rand)
print(arr_sort)

In [ ]:
print(arr_rand)
arr_sort = np.sort(arr_rand, axis = 0)
print(arr_sort)

In [ ]:
# insert

print(arr_sort)

In [ ]:
arr_ins = np.insert(arr_sort, 15, [0,0,0,0,0]).reshape(5,5)

print(arr_ins)

In [ ]:
arr_flat = arr_ins.flatten()
print(arr_flat)

In [ ]:
arr_flat_ins = np.insert(arr_flat, 4, 20)

print(arr_flat_ins)

In [ ]:
#Transpose

In [ ]:
arr_1 = np.arange(1,25).reshape(4,6)

arr_1

In [ ]:
arr_2 = arr_1.transpose() #Returns only a view of the transposed array and does not have a inplace parameter - so to see
# the effect - must save the transposed view to a variable.

arr_2

In [ ]:
arr_2[2][3] = 777

arr_2

In [ ]:
arr_1

In [ ]:
import copy

arr_3 = copy.deepcopy(arr_1.transpose())

In [ ]:
arr_3

In [ ]:
arr_3[0][0] = 1

arr_3

In [ ]:
arr_1

In [ ]:
arr_1 = np.arange(1,25).reshape(2,3,4)

arr_1

In [ ]:
arr_2 = np.transpose(arr_1, (1,0,2))

arr_2.shape

In [ ]:
arr_3 = np.transpose(arr_1, (1,2,0))
arr_3.shape

In [ ]:
np.dot()

In [ ]:
print(dir(np))